name: Build Webview
on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Which OS to build webview with'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - windows-latest
        - macos-latest
jobs: 
  build:
    name: "build ${{ inputs.os }}"
    runs-on: ${{ inputs.os }}
    steps:
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
