name: Build Webview
on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Which OS to build webview with'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - Linux
        - Windows
        - MacOS
jobs:
  build_linux:
    if: ${{ inputs.os }} == Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/build/webview
    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4
    - name: Build webview for ${{ inputs.os }}
      run: ./linux.sh
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
