name: Build Webview
on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Which OS to build webview with'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - windows-latest
        - macos-latest
jobs:
  build_linux:
    runs-on: ${{ inputs.os }}
    steps:
    - name: build ${{ inputs.os }}
      run: |
        mkdir -p path/to/artifact
        echo hello > path/to/artifact/world.txt 
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
