name: Build Webview
on: []
jobs: 
    build_linux:
        name: ubuntu latest
        runs-on: ubuntu-latest
        steps:
        - run: | 
            mkdir -p path/to/artifact
            echo hello > path/to/artifact/world.txt
        - uses: actions/upload-artifact@v4
            with:
                name: my-artifact
                path: path/to/artifact/world.txt
